In [7]:
import pandas as py
import numpy as np
import json
import pickle
import pandas.io.json as pdio

In [2]:
fo = open("testdata.obj", 'rb')
data = pickle.load(fo)

In [6]:
 data2 = json.loads(data)["data"]
data2[:3]

[{'id': '20a10f64465f46700a1d722a_0|20a10f64465f46700a1d722a_1',
  'countryFrom': {'code': 'US', 'name': 'United States'},
  'countryTo': {'code': 'GB', 'name': 'United Kingdom'},
  'bags_price': {},
  'baglimit': {'hand_width': 23,
   'hand_height': 36,
   'hand_length': 56,
   'hand_weight': 10},
  'dTime': 1556564400,
  'aTime': 1556608200,
  'dTimeUTC': 1556578800,
  'p1': 1,
  'p2': 1,
  'p3': 1,
  'aTimeUTC': 1556604600,
  'price': 1548,
  'flyFrom': 'JFK',
  'mapIdfrom': 'new-york',
  'mapIdto': 'london',
  'flyTo': 'LHR',
  'distance': 5545.54,
  'cityFrom': 'New York',
  'cityTo': 'London',
  'route': [{'id': '20a10f64465f46700a1d722a_0',
    'combination_id': '20a10f64465f46700a1d722a',
    'return': 0,
    'original_return': 0,
    'source': 'deprecated',
    'found_on': 'deprecated',
    'price': 1,
    'aTime': 1556608200,
    'dTime': 1556564400,
    'aTimeUTC': 1556604600,
    'dTimeUTC': 1556578800,
    'mapIdfrom': 'new-york',
    'mapIdto': 'london',
    'cityTo': 'London',
    'cityFrom': 'New York',
    'flyTo': 'LHR',
    'airline': 'AA',
    'operating_carrier': 'BA',
    'equipment': '744',
    'flyFrom': 'JFK',
    'latFrom': 40.639722,
    'lngFrom': -73.778889,
    'latTo': 51.4775,
    'lngTo': -0.461389,
    'flight_no': 6139,
    'vehicle_type': 'aircraft',
    'refresh_timestamp': 1555683538,
    'bags_recheck_required': False,
    'guarantee': False,
    'fare_classes': 'L',
    'fare_basis': 'LLX7C7M5',
    'fare_family': '',
    'last_seen': 1555683538}],
  'routes': [['JFK', 'LHR']],
  'airlines': ['AA'],
  'nightsInDest': None,
  'pnr_count': 1,
  'transfers': [],
  'has_airport_change': False,
  'fly_duration': '7h 10m',
  'duration': {'departure': 25800, 'return': 0, 'total': 25800},
  'hashtags': ['evening',
   'monday',
   'direct',
   'duration:7-8',
   'departure:19-20',
   'arrival:7-8'],
  'facilitated_booking_available': False,
  'conversion': {'EUR': 1386, 'USD': 1548},
  'booking_token': '2ecZSda9kty0xF/hxcwoiFdUDxMYRscYX2JssMhrILNuotgIqMiRnJ8pGLNuJVy+dc2SIxu+AwDet7OLjnaXfv0Eq94z8o7PAxzCTmNX7MXWVVZJs5skdnWzVrwj3Ne7R1pvtP7ximGTo1sq+37csDka1WZfs5hi6fYHpe8TvmC9CR1+z0ierlvDT83//0LzfkxM3CKSQTQMLDiZ6HsZGpqYWF1mHqoP9t1ei82APTDHQr1/DXsA5BcQngcufjUcqW+U/qbGmm0WoC1n7rx91L2SBbN17ix7Ng4eCk4bun5z91ZNf8WAyGkxpqAV+dp6fniQXXHtekwCe5ar5YgL89fSJrujlGStA7s0NOaoU4HBKu7fbtrFuIYQlBfA2TWWZ6xgQNfeiHHDmWzJFkmg0670r5lrh/ZQj3KBQlxGkE4kq0f/k1FXFjG5xpqbslBS5O/6BhIIBpNKo9iC+upoVyiAtyzcPpwMiftBqN/pAgiXIUiI3svOqtZVxqWGiKGLCbzk8AdPD4ZGbqkRFdxK9HfP95tfng+5txOJ/8OK9PyCr0dyPw+Tykc8/TLtkp4rvTXdiQcfSwCmaCaYkKznNuGon2s4ViaWiZnrAczwwyR3Yxcq/+DVc32XXxDTsA43nfy6jnz9dCCxrnsCTeinPazXCTiunp3Da4ALskKUd4+OclMEKxK2itHLWbMe7qHt+XpBnUlugKGlOa4eiyEZR3u+hqRer2AQkBfIFNJgiDkq6RPhuWH6fRAg8JoB1b8MBWY0VhSReAr8/XcQVIWDG/IAE974ZmOm7vA/ojZRCSFdodmBGLm+1m1OjrpI3INP0d+QmQpnngOhHMg3vj0+mjjTsL3DCmU8nGkmHuJrQ9g+dMPMCvFPkXPHN8CfTknWKyQjUmHvVpRhY6Mx4ZvAFzUvOQYDaQcdsINL14e+oz0ntzZL+qkriQSGfGuxm0PCKm0ZAP9b/ZefCn4XR6WiLA==',
  'quality': 1455.33316,
  'found_on': ['deprecated']},
 {'id': '20a10f64465e4672d052d437_0|20a10f64465e4672d052d437_1|20a10f64465e4672d052d437_2',
  'countryFrom': {'code': 'US', 'name': 'United States'},
  'countryTo': {'code': 'GB', 'name': 'United Kingdom'},
  'bags_price': {},
  'baglimit': {'hand_width': 23,
   'hand_height': 36,
   'hand_length': 56,
   'hand_weight': 10},
  'dTime': 1556490600,
  'aTime': 1556535000,
  'dTimeUTC': 1556505000,
  'p1': 1,
  'p2': 1,
  'p3': 1,
  'aTimeUTC': 1556531400,
  'price': 1654,
  'flyFrom': 'JFK',
  'mapIdfrom': 'new-york',
  'mapIdto': 'london',
  'flyTo': 'LHR',
  'distance': 5545.54,
  'cityFrom': 'New York',
  'cityTo': 'London',
  'route': [{'id': '20a10f64465e4672d052d437_0',
    'combination_id': '20a10f64465e4672d052d437',
    'return': 0,
    'original_return': 0,
    'source': 'deprecated',
    'found_on': 'deprecated',
    'price': 1,
    'aTime': 1556535000,
    'dTime': 1556490600,
    'aTimeUTC': 1556531400,
    'dTimeUTC': 1556505000,
    'mapIdfrom': 'new-york',
    'mapIdto': 'london',
    'cityTo': 'London',
    'cityFrom': 'New York',
    'flyTo': 'LHR',
    'airline': 'AA',
    'operating_carrier': 'AA',
    'equipment': '77W',
    'flyFrom': 'JFK',
    'latFrom': 40.639722,
    'lngFrom': -73.778889,
    'latTo': 51.4775,
    'lngTo': -0.461389,
    'flight_no': 104,
    'vehicle_type': 'aircraft',
    'refresh_timestamp': 1555619643,
    'bags_recheck_required': False,
    'guarantee': False,
    'fare_classes': 'L',
    'fare_basis': 'LLX7C7M5',
    'fare_family': '',
    'last_seen': 1555619643}],
  'routes': [['JFK', 'LHR']],
  'airlines': ['AA'],
  'nightsInDest': None,
  'pnr_count': 1,
  'transfers': [],
  'has_airport_change': False,
  'fly_duration': '7h 20m',
  'duration': {'departure': 26400, 'return': 0, 'total': 26400},
  'hashtags': ['evening',
   'sunday',
   'direct',
   'duration:7-8',
   'departure:22-23',
   'arrival:10-11'],
  'facilitated_booking_available': False,
  'conversion': {'EUR': 1481, 'USD': 1654},
  'booking_token': '2ecZSda9kty0xF/hxcwoiFdUDxMYRscYX2JssMhrILNuotgIqMiRnJ8pGLNuJVy+dc2SIxu+AwDet7OLjnaXfv0Eq94z8o7PAxzCTmNX7MXWVVZJs5skdnWzVrwj3Ne70Rj0VtvxgrMpW+rV8og3XuXAm41xDTPEMLXrNmxAzRmWFaPpZJJCyFFIWzgy39x0ajUCAte71gb7OOuYujLCpvSGEVfnCtd2G2MVjrJGUVgaZyOZiGxJxa2CvbNBLupI8SL8HEVjchtxg7M3U79dDg0dxm0IPJoa4E3vK7QftUUI+EtzQEw3qm6CqkRTbP8zlW2yMTPjtdLeZg/PvYQzppfPFpTjMmZr4f+leZwRKh8S1Dk7Y1OixBkuCE7tGyU0g2/cLH2irLPS+Q7rUU5n3O+bn9YLiFnq1bezMjo9myelDQVXxPYExkj6JV+2p8MgxvQUmTQsmigqrum9o42+Zg61kCH1iOyU2yNmIOXnZ3DHxuyAW+ndrSgFimqT14O4dsdv3zNc6USJYM0aJm0NDpGBO7YY3DPX26EUCFhDmUYzwk7gktrlgVgmWIkbHhF3kx6OjH0v5ez50sSXks9wWUiR7pmWCnSqAdxzQrDBLR8Agj3rCZFoN1r/nVjIqK13R8VD6XrgmbehgIH8lKkUFm+FbdSxGuSrnd3E2FTMAXrPQ8YjZ4NLR2isUzcaOhvxJ1M5SOnQU4GGt/mPJQk0RjDLUEdBerQnq+tFioB2XO4isT9PrKrg5zx5E/tfkgS/X83bbSluyr9E4XPlhDewO/e8f9sTvMDqBDMJL8tki4qMC6Ji96Mf1rdpkFQpe46MbRQxPtzcoB+7aJxPE0CoVtih3uGvUUhdxNc13fkndmmsmVikeclgY0IODO7aM+pQ1o/74kitWQgkh+ZjY/kaOFcMpKjc61ddTS3PimJb10y6Q4+WnmeWRG3MwRlGF9xb+pAfG7r/AWRYCq982eb0tnP/aszvE4MwYyiG9GTkdgnRXgG6t80CnGXfAxPOibeJPnOIxyUbdJnnyBXPtbEwEQ3kXSbYIWTiOIedxr2tcnRqPS7a6Nq7ztx6hoV4jtQe',
  'quality': 1551.66649,
  'found_on': ['deprecated']},
 {'id': '20a10f64465f4679d7bc75f9_0|20a10f64465f4679d7bc75f9_1',
  'countryFrom': {'code': 'US', 'name': 'United States'},
  'countryTo': {'code': 'GB', 'name': 'United Kingdom'},
  'bags_price': {'1': 0.0, '2': 214.99},
  'baglimit': {'hold_width': 27,
   'hold_height': 52,
   'hold_length': 78,
   'hold_dimensions_sum': 157,
   'hold_weight': 23,
   'hand_width': 23,
   'hand_height': 35,
   'hand_length': 56,
   'hand_weight': 10},
  'dTime': 1556575200,
  'aTime': 1556619300,
  'dTimeUTC': 1556589600,
  'p1': 1,
  'p2': 1,
  'p3': 1,
  'aTimeUTC': 1556615700,
  'price': 1656,
  'flyFrom': 'JFK',
  'mapIdfrom': 'new-york',
  'mapIdto': 'london',
  'flyTo': 'LHR',
  'distance': 5545.54,
  'cityFrom': 'New York',
  'cityTo': 'London',
  'route': [{'id': '20a10f64465f4679d7bc75f9_0',
    'combination_id': '20a10f64465f4679d7bc75f9',
    'return': 0,
    'original_return': 0,
    'source': 'deprecated',
    'found_on': 'deprecated',
    'price': 1,
    'aTime': 1556619300,
    'dTime': 1556575200,
    'aTimeUTC': 1556615700,
    'dTimeUTC': 1556589600,
    'mapIdfrom': 'new-york',
    'mapIdto': 'london',
    'cityTo': 'London',
    'cityFrom': 'New York',
    'flyTo': 'LHR',
    'airline': 'DL',
    'operating_carrier': 'VS',
    'equipment': '333',
    'flyFrom': 'JFK',
    'latFrom': 40.639722,
    'lngFrom': -73.778889,
    'latTo': 51.4775,
    'lngTo': -0.461389,
    'flight_no': 4377,
    'vehicle_type': 'aircraft',
    'refresh_timestamp': 0,
    'bags_recheck_required': False,
    'guarantee': False,
    'fare_classes': 'K',
    'fare_basis': 'KL1J77M2',
    'fare_family': '',
    'last_seen': 1555940091}],
  'routes': [['JFK', 'LHR']],
  'airlines': ['DL'],
  'nightsInDest': None,
  'pnr_count': 1,
  'transfers': [],
  'has_airport_change': False,
  'fly_duration': '7h 15m',
  'duration': {'departure': 26100, 'return': 0, 'total': 26100},
  'hashtags': ['evening',
   'monday',
   'direct',
   'duration:7-8',
   'departure:22-23',
   'arrival:10-11'],
  'facilitated_booking_available': True,
  'conversion': {'EUR': 1483, 'USD': 1656},
  'booking_token': '2ecZSda9kty0xF/hxcwoiFdUDxMYRscYX2JssMhrILNuotgIqMiRnJ8pGLNuJVy+dc2SIxu+AwDet7OLjnaXfv0Eq94z8o7PAxzCTmNX7MXWVVZJs5skdnWzVrwj3Ne7E//CRdxK34Ioz+uX8I2g8D00mxqodprBpiGD2sqRs4btCjCe3JoyxiKaGhsqbTLZoymmQrzSwrSpuNY0/znyn+RSxb81AtjpSAbLWRDEhBfkvipfSPXdKHWznXVtW7Pwxa0Kcuyc55abHBgxvuWTwTgYreIDbO5JvsRRWCBYDsgLCEzUoCUIqCBn6mRhS5dn/JPUyElx2YcFyuheSsiEpT4gWfZ3vFrqBESO/KwHeVy93bkjyvnk9u3TStLMWJf7Wd6uen4bfzhcCwf4TCSJ7x+1a0fRCWntYZcABbUz1N6/TwK3fNJEuISnts8ywfPhDdEC7zB9FhIcO3VI0gcE/X5RanByNGdpM9DtdEDtrtJKT05D2XNADRh+mb2q17a/Y/ZBhnwVW2u/P6fF5n/M7IOJD+CKe+XkSpJvPqJxVDK9cGVDI/z66Ltk78SJCFwdJ+0YxvOxpO0tY8J6R7DCJyHZIuXUF76aCa3TyNmLQDibgzK97SSaCmFLVTwMQl6Kn9MvNfQvCHwlisolhlnnO8821ismOF63tFvJfl6SqSrC7miNLpwBRi9aA1V/UQD03aBRnk62gxDyfwRx+WAW1e07xOibuPuMUQUeauMHh+BsiztZlPBEsok8+JlEFvCmEGfJYjtuLedRseAc0bmMtA6XeLK0Y9VT3cxYiCak6VM7PzjPWAPBzbKotwqU4NbG21Bvr00t6C2KlDkNtOyenBGx8WGdjBInMsEjigfbKQv/ncaqkIge/EaiwNFY2AuEDcAUpN/nJIYP04aui7UugeJu4YvW5F04AzfXcrXcUqD9/gD2uMfnE/dmSLFTO2yS',
  'quality': 1552.999825,
  'found_on': ['deprecated']}]

In [9]:
 df1 = pdio.json_normalize(data2)
df1

,aTime,aTimeUTC,airlines,baglimit.hand_height,baglimit.hand_length,baglimit.hand_weight,baglimit.hand_width,baglimit.hold_dimensions_sum,baglimit.hold_height,baglimit.hold_length,...,nightsInDest,p1,p2,p3,pnr_count,price,quality,route,routes,transfers
0,1556608200,1556604600,[AA],36,56,10,23,NaN,NaN,NaN,...,None,1,1,1,1,1548,1455.333160,"[{'id': '20a10f64465f46700a1d722a_0', 'combina...","[[JFK, LHR]]",[]
1,1556535000,1556531400,[AA],36,56,10,23,NaN,NaN,NaN,...,None,1,1,1,1,1654,1551.666490,"[{'id': '20a10f64465e4672d052d437_0', 'combina...","[[JFK, LHR]]",[]
2,1556619300,1556615700,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1656,1552.999825,"[{'id': '20a10f64465f4679d7bc75f9_0', 'combina...","[[JFK, LHR]]",[]
3,1556705700,1556702100,[KL],35,55,8,23,157.0,52.0,78.0,...,None,1,1,1,1,1668,1563.999825,"[{'id': '20a10f6446604673b8347461_0', 'combina...","[[JFK, LHR]]",[]
4,1556622300,1556618700,[AY],36,56,6,23,NaN,NaN,NaN,...,None,1,1,1,1,1670,1564.666495,"[{'id': '20a10f64465f4679d3f0295f_0', 'combina...","[[JFK, LHR]]",[]
5,1556653500,1556649900,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1646.666500,"[{'id': '20a10f6446600000291fa41a_0', 'combina...","[[JFK, LHR]]",[]
6,1556568600,1556565000,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1764,1647.333165,"[{'id': '20a10f64465f00001fb6aad1_0', 'combina...","[[JFK, LHR]]",[]
7,1556655000,1556651400,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1764,1647.333165,"[{'id': '20a10f64466000008866bce6_0', 'combina...","[[JFK, LHR]]",[]
8,1556662200,1556658600,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1647.333165,"[{'id': '20a10f6446600000157e83a0_0', 'combina...","[[JFK, LHR]]",[]
9,1556708700,1556705100,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1648.666495,"[{'id': '20a10f64466000004e5251cb_0', 'combina...","[[JFK, LHR]]",[]
10,1556691600,1556688000,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1649.999825,"[{'id': '20a10f64466000002025253b_0', 'combina...","[[JFK, LHR]]",[]
11,1556702100,1556698500,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1764,1649.999825,"[{'id': '20a10f64466000008f0b78ff_0', 'combina...","[[JFK, LHR]]",[]
12,1556700300,1556696700,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1764,1649.999825,"[{'id': '20a10f6446600000b48b5656_0', 'combina...","[[JFK, LHR]]",[]
13,1556524200,1556520600,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1764,1650.666490,"[{'id': '20a10f64465e0000cdfa9587_0', 'combina...","[[JFK, LHR]]",[]
14,1556696400,1556692800,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1650.666490,"[{'id': '20a10f6446600000c0f0cc25_0', 'combina...","[[JFK, LHR]]",[]
15,1556707800,1556704200,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1764,1650.666490,"[{'id': '20a10f64466000002748e122_0', 'combina...","[[JFK, LHR]]",[]
16,1556695200,1556691600,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,1764,1650.666490,"[{'id': '20a10f6446600000427a5c5f_0', 'combina...","[[JFK, LHR]]",[]
17,1556697000,1556693400,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1764,1650.666490,"[{'id': '20a10f6446600000fc879768_0', 'combina...","[[JFK, LHR]]",[]
18,1556567100,1556563500,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1776,1657.666500,"[{'id': '20a10f64465f00001272f79c_0', 'combina...","[[JFK, LHR]]",[]
19,1556692200,1556688600,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1776,1658.999830,"[{'id': '20a10f64466000002c41ec90_0', 'combina...","[[JFK, LHR]]",[]
20,1556535900,1556532300,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1776,1659.666495,"[{'id': '20a10f64465e0000636c9380_0', 'combina...","[[JFK, LHR]]",[]
21,1556703300,1556699700,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1776,1659.666495,"[{'id': '20a10f6446600000c52249a5_0', 'combina...","[[JFK, LHR]]",[]
22,1556698800,1556695200,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1776,1660.333160,"[{'id': '20a10f64466000002b2c2889_0', 'combina...","[[JFK, LHR]]",[]
23,1556615700,1556612100,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1786,1669.999825,"[{'id': '20a10f64465f000049ec0d57_0', 'combina...","[[JFK, LHR]]",[]
24,1556613900,1556610300,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1786,1669.999825,"[{'id': '20a10f64465f00002b16a24a_0', 'combina...","[[JFK, LHR]]",[]
25,1556610600,1556607000,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1786,1670.666490,"[{'id': '20a10f64465f00000b6d7c60_0', 'combina...","[[JFK, LHR]]",[]
26,1556605500,1556601900,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,1786,1671.333155,"[{'id': '20a10f64465f00008a206af6_0', 'combina...","[[JFK, LHR]]",[]
27,1556575800,1556572200,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1787,1668.333165,"[{'id': '20a10f64465f00001082538f_0', 'combina...","[[JFK, LHR]]",[]
28,1556526000,1556522400,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1787,1670.333160,"[{'id': '20a10f64465e0000b5c3ecd0_0', 'combina...","[[JFK, LHR]]",[]
29,1556605200,1556601600,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1787,1670.999825,"[{'id': '20a10f64465f0000a8312d08_0', 'combina...","[[JFK, LHR]]",[]
30,1556610000,1556606400,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1787,1671.666490,"[{'id': '20a10f64465f00004152883d_0', 'combina...","[[JFK, LHR]]",[]
31,1556616900,1556613300,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1790,1671.666495,"[{'id': '20a10f64465f000080dbce88_0', 'combina...","[[JFK, LHR]]",[]
32,1556621400,1556617800,[AY],42,63,6,22,158.0,50.0,70.0,...,None,1,1,1,1,1790,1673.666490,"[{'id': '20a10f64465f0000d0a20a2a_0', 'combina...","[[JFK, LHR]]",[]
33,1556530500,1556526900,[AA],36,56,10,23,NaN,NaN,NaN,...,None,1,1,1,1,1799,1679.666495,"[{'id': '20a10f64465e0000b7ff3a10_0', 'combina...","[[JFK, LHR]]",[]
34,1556612400,1556608800,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,1803,1684.333160,"[{'id': '20a10f64465f0000a3907d1d_0', 'combina...","[[JFK, LHR]]",[]
35,1556528700,1556525100,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,2855,2625.666495,"[{'id': '20a10f64465e0000e4f48f4f_0', 'combina...","[[JFK, LHR]]",[]
36,1556605800,1556602200,[BA],45,56,23,25,NaN,75.0,95.0,...,None,1,1,1,1,2880,2647.999830,"[{'id': '20a10f64465f0000a4fdb904_0', 'combina...","[[JFK, LHR]]",[]
37,1556527500,1556523900,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,3324,3047.999825,"[{'id': '20a10f64465e00003d453387_0', 'combina...","[[JFK, LHR]]",[]
38,1556532900,1556529300,[VS],36,56,10,23,NaN,75.0,95.0,...,None,1,1,1,1,3324,3047.999825,"[{'id': '20a10f64465e0000e2a6d4f8_0', 'combina...","[[JFK, LHR]]",[]
39,1556691900,1556688300,[DL],35,56,10,23,157.0,52.0,78.0,...,None,1,1,1,1,3523,3227.333155,"[{'id': '20a10f6446604670fd2aec18_0', 'combina...","[[JFK, LHR]]",[]

In [ ]:
df2 = pdio.json_normalize(data=